import React, { useState, useEffect } from "react";
import Select from "react-select";

import { motion } from "framer-motion";
const RandomSongGenerator = ({ onSelect }) => {

const songs = [
    { title: "Bohemian Rhapsody", artist: "Queen", decade: "1970s" },
    { title: "White Christmas", artist: "Bing Crosby", decade: "1940s" },
    { title: "Boogie Woogie Bugle Boy", artist: "The Andrews Sisters", decade: "1940s" },
    { title: "In the Mood", artist: "Glenn Miller", decade: "1940s" },
    { title: "Moonlight Serenade", artist: "Glenn Miller", decade: "1940s" },
    { title: "Don't Sit Under the Apple Tree", artist: "The Andrews Sisters", decade: "1940s" },
    { title: "I'll Be Seeing You", artist: "Billie Holiday", decade: "1940s" },
    { title: "Sentimental Journey", artist: "Doris Day & Les Brown", decade: "1940s" },
    { title: "You Always Hurt the One You Love", artist: "The Mills Brothers", decade: "1940s" },
    { title: "Swinging on a Star", artist: "Bing Crosby", decade: "1940s" },
    { title: "A String of Pearls", artist: "Glenn Miller", decade: "1940s" },
    { title: "Chattanooga Choo Choo", artist: "Glenn Miller & His Orchestra", decade: "1940s" },
    { title: "It Had to Be You", artist: "Helen Forrest & Dick Haymes", decade: "1940s" },
    { title: "I'm Looking Over a Four Leaf Clover", artist: "Art Mooney", decade: "1940s" },
    { title: "Accentuate the Positive", artist: "Johnny Mercer", decade: "1940s" },
    { title: "Take the 'A' Train", artist: "Duke Ellington", decade: "1940s" },
    { title: "Some Enchanted Evening", artist: "Perry Como", decade: "1940s" },
    { title: "Let’s Take the Long Way Home", artist: "Jo Stafford", decade: "1940s" },
    { title: "Paper Doll", artist: "The Mills Brothers", decade: "1940s" },
    { title: "G.I. Jive", artist: "Louis Jordan", decade: "1940s" },
    { title: "Buttons and Bows", artist: "Dinah Shore", decade: "1940s" },
    { title: "I've Heard That Song Before", artist: "Helen Forrest & Harry James", decade: "1940s" },
    { title: "Rum and Coca-Cola", artist: "The Andrews Sisters", decade: "1940s" },
    { title: "Besame Mucho", artist: "Consuelo Velázquez", decade: "1940s" },
    { title: "All or Nothing at All", artist: "Frank Sinatra", decade: "1940s" },
    { title: "Nature Boy", artist: "Nat King Cole", decade: "1940s" },
    { title: "I Wonder Who’s Kissing Her Now", artist: "Perry Como", decade: "1940s" },
    { title: "I Don’t Want to Set the World on Fire", artist: "The Ink Spots", decade: "1940s" },
    { title: "It’s Been a Long, Long Time", artist: "Bing Crosby", decade: "1940s" },
    { title: "Juke Box Saturday Night", artist: "Glenn Miller", decade: "1940s" },
    { title: "Shoo-Shoo Baby", artist: "The Andrews Sisters", decade: "1940s" },
    { title: "I’ll Get By", artist: "Harry James & Dick Haymes", decade: "1940s" },
    { title: "On the Sunny Side of the Street", artist: "Tommy Dorsey & The Sentimentalists", decade: "1940s" },
    { title: "I’m Beginning to See the Light", artist: "Duke Ellington", decade: "1940s" },
    { title: "That Lucky Old Sun", artist: "Frankie Laine", decade: "1940s" },
    { title: "Stormy Weather", artist: "Lena Horne", decade: "1940s" },
    { title: "You’d Be So Nice to Come Home To", artist: "Dinah Shore", decade: "1940s" },
    { title: "When You Wish Upon a Star", artist: "Cliff Edwards", decade: "1940s" },
    { title: "Deep in the Heart of Texas", artist: "Bing Crosby", decade: "1940s" },
    { title: "I Love You for Sentimental Reasons", artist: "Nat King Cole", decade: "1940s" },
    { title: "Harbor Lights", artist: "Sammy Kaye", decade: "1940s" },
    { title: "Personality", artist: "Johnny Mercer", decade: "1940s" },
    { title: "Time After Time", artist: "Frank Sinatra", decade: "1940s" },
    { title: "A Nightingale Sang in Berkeley Square", artist: "Vera Lynn", decade: "1940s" },
    { title: "It’s Only a Paper Moon", artist: "Ella Fitzgerald", decade: "1940s" },
    { title: "Praise the Lord and Pass the Ammunition", artist: "Kay Kyser", decade: "1940s" },
    { title: "The Anniversary Waltz", artist: "Bing Crosby", decade: "1940s" },
    { title: "A Kiss to Build a Dream On", artist: "Louis Armstrong", decade: "1940s" },
    { title: "Twilight Time", artist: "The Three Suns", decade: "1940s" },
    { title: "Jailhouse Rock", artist: "Elvis Presley", decade: "1950s" },
    { title: "Hound Dog", artist: "Elvis Presley", decade: "1950s" },
    { title: "Johnny B. Goode", artist: "Chuck Berry", decade: "1950s" },
    { title: "Great Balls of Fire", artist: "Jerry Lee Lewis", decade: "1950s" },
    { title: "Rock Around the Clock", artist: "Bill Haley & His Comets", decade: "1950s" },
    { title: "Tutti Frutti", artist: "Little Richard", decade: "1950s" },
    { title: "Peggy Sue", artist: "Buddy Holly", decade: "1950s" },
    { title: "Blueberry Hill", artist: "Fats Domino", decade: "1950s" },
    { title: "Why Do Fools Fall in Love", artist: "Frankie Lymon & The Teenagers", decade: "1950s" },
    { title: "Love Me Tender", artist: "Elvis Presley", decade: "1950s" },
    { title: "Chantilly Lace", artist: "The Big Bopper", decade: "1950s" },
    { title: "Bye Bye Love", artist: "The Everly Brothers", decade: "1950s" },
    { title: "La Bamba", artist: "Ritchie Valens", decade: "1950s" },
    { title: "Wake Up Little Susie", artist: "The Everly Brothers", decade: "1950s" },
    { title: "Whole Lotta Shakin' Goin' On", artist: "Jerry Lee Lewis", decade: "1950s" },
    { title: "All Shook Up", artist: "Elvis Presley", decade: "1950s" },
    { title: "That’ll Be the Day", artist: "Buddy Holly & The Crickets", decade: "1950s" },
    { title: "Little Darlin'", artist: "The Diamonds", decade: "1950s" },
    { title: "At the Hop", artist: "Danny & The Juniors", decade: "1950s" },
    { title: "Earth Angel", artist: "The Penguins", decade: "1950s" },
    { title: "Splish Splash", artist: "Bobby Darin", decade: "1950s" },
    { title: "Rockin’ Robin", artist: "Bobby Day", decade: "1950s" },
    { title: "Since I Don’t Have You", artist: "The Skyliners", decade: "1950s" },
    { title: "Sea of Love", artist: "Phil Phillips", decade: "1950s" },
    { title: "Sh-Boom", artist: "The Chords", decade: "1950s" },
    { title: "Tequila", artist: "The Champs", decade: "1950s" },
    { title: "Yakety Yak", artist: "The Coasters", decade: "1950s" },
    { title: "Only You", artist: "The Platters", decade: "1950s" },
    { title: "Unchained Melody", artist: "Al Hibbler", decade: "1950s" },
    { title: "Come Go With Me", artist: "The Del-Vikings", decade: "1950s" },
    { title: "Summertime Blues", artist: "Eddie Cochran", decade: "1950s" },
    { title: "Lollipop", artist: "The Chordettes", decade: "1950s" },
    { title: "Mr. Sandman", artist: "The Chordettes", decade: "1950s" },
    { title: "Diana", artist: "Paul Anka", decade: "1950s" },
    { title: "A Teenager in Love", artist: "Dion and The Belmonts", decade: "1950s" },
    { title: "Poison Ivy", artist: "The Coasters", decade: "1950s" },
    { title: "School Day", artist: "Chuck Berry", decade: "1950s" },
    { title: "Stagger Lee", artist: "Lloyd Price", decade: "1950s" },
    { title: "Maybe", artist: "The Chantels", decade: "1950s" },
    { title: "Book of Love", artist: "The Monotones", decade: "1950s" },
    { title: "Lonely Teardrops", artist: "Jackie Wilson", decade: "1950s" },
    { title: "Silhouettes", artist: "The Rays", decade: "1950s" },
    { title: "Oh Boy!", artist: "Buddy Holly", decade: "1950s" },
    { title: "Rave On", artist: "Buddy Holly", decade: "1950s" },
    { title: "Be-Bop-A-Lula", artist: "Gene Vincent", decade: "1950s" },
    { title: "Blue Suede Shoes", artist: "Carl Perkins", decade: "1950s" },
    { title: "Rebel Rouser", artist: "Duane Eddy", decade: "1950s" },
    { title: "Love Letters in the Sand", artist: "Pat Boone", decade: "1950s" },
    { title: "Hey Jude", artist: "The Beatles", decade: "1960s" },
    { title: "I Can't Get No Satisfaction", artist: "The Rolling Stones", decade: "1960s" },
    { title: "Good Vibrations", artist: "The Beach Boys", decade: "1960s" },
    { title: "Respect", artist: "Aretha Franklin", decade: "1960s" },
    { title: "Purple Haze", artist: "Jimi Hendrix", decade: "1960s" },
    { title: "Like a Rolling Stone", artist: "Bob Dylan", decade: "1960s" },
    { title: "My Girl", artist: "The Temptations", decade: "1960s" },
    { title: "A Whiter Shade of Pale", artist: "Procol Harum", decade: "1960s" },
    { title: "Somebody to Love", artist: "Jefferson Airplane", decade: "1960s" },
    { title: "California Dreamin'", artist: "The Mamas & The Papas", decade: "1960s" },
    { title: "The Sound of Silence", artist: "Simon & Garfunkel", decade: "1960s" },
    { title: "I Heard It Through the Grapevine", artist: "Marvin Gaye", decade: "1960s" },
    { title: "Light My Fire", artist: "The Doors", decade: "1960s" },
    { title: "Suspicious Minds", artist: "Elvis Presley", decade: "1960s" },
    { title: "Stand by Me", artist: "Ben E. King", decade: "1960s" },
    { title: "Fortunate Son", artist: "Creedence Clearwater Revival", decade: "1960s" },
    { title: "The Twist", artist: "Chubby Checker", decade: "1960s" },
    { title: "Sweet Caroline", artist: "Neil Diamond", decade: "1960s" },
    { title: "Twist and Shout", artist: "The Beatles", decade: "1960s" },
    { title: "Born to Be Wild", artist: "Steppenwolf", decade: "1960s" },
    { title: "You Really Got Me", artist: "The Kinks", decade: "1960s" },
    { title: "Build Me Up Buttercup", artist: "The Foundations", decade: "1960s" },
    { title: "Runaway", artist: "Del Shannon", decade: "1960s" },
    { title: "Runaround Sue", artist: "Dion", decade: "1960s" },
    { title: "Ain't No Mountain High Enough", artist: "Marvin Gaye & Tammi Terrell", decade: "1960s" },
    { title: "Can't Help Falling in Love", artist: "Elvis Presley", decade: "1960s" },
    { title: "Help!", artist: "The Beatles", decade: "1960s" },
    { title: "The House of the Rising Sun", artist: "The Animals", decade: "1960s" },
    { title: "Do Wah Diddy Diddy", artist: "Manfred Mann", decade: "1960s" },
    { title: "I'm a Believer", artist: "The Monkees", decade: "1960s" },
    { title: "Proud Mary", artist: "Creedence Clearwater Revival", decade: "1960s" },
    { title: "Wouldn't It Be Nice", artist: "The Beach Boys", decade: "1960s" },
    { title: "I Got You Babe", artist: "Sonny & Cher", decade: "1960s" },
    { title: "Oh, Pretty Woman", artist: "Roy Orbison", decade: "1960s" },
    { title: "Soul Man", artist: "Sam & Dave", decade: "1960s" },
    { title: "Crying", artist: "Roy Orbison", decade: "1960s" },
    { title: "She Loves You", artist: "The Beatles", decade: "1960s" },
    { title: "Stop! In the Name of Love", artist: "The Supremes", decade: "1960s" },
    { title: "Be My Baby", artist: "The Ronettes", decade: "1960s" },
    { title: "Baby Love", artist: "The Supremes", decade: "1960s" },
    { title: "Where Did Our Love Go", artist: "The Supremes", decade: "1960s" },
    { title: "Sugar, Sugar", artist: "The Archies", decade: "1960s" },
    { title: "Then He Kissed Me", artist: "The Crystals", decade: "1960s" },
    { title: "It's Now or Never", artist: "Elvis Presley", decade: "1960s" },
    { title: "Green Onions", artist: "Booker T. & the M.G.'s", decade: "1960s" },
    { title: "Hey Joe", artist: "Jimi Hendrix", decade: "1960s" },
    { title: "Daydream Believer", artist: "The Monkees", decade: "1960s" },
    { title: "Glad All Over", artist: "The Dave Clark Five", decade: "1960s" },
    { title: "Wooly Bully", artist: "Sam the Sham & The Pharaohs", decade: "1960s" },
    { title: "Bohemian Rhapsody", artist: "Queen", decade: "1970s" },
    { title: "Stairway to Heaven", artist: "Led Zeppelin", decade: "1970s" },
    { title: "Hotel California", artist: "Eagles", decade: "1970s" },
    { title: "Stayin' Alive", artist: "Bee Gees", decade: "1970s" },
    { title: "Dream On", artist: "Aerosmith", decade: "1970s" },
    { title: "Imagine", artist: "John Lennon", decade: "1970s" },
    { title: "Superstition", artist: "Stevie Wonder", decade: "1970s" },
    { title: "Sweet Home Alabama", artist: "Lynyrd Skynyrd", decade: "1970s" },
    { title: "We Will Rock You", artist: "Queen", decade: "1970s" },
    { title: "American Pie", artist: "Don McLean", decade: "1970s" },
    { title: "Let’s Stay Together", artist: "Al Green", decade: "1970s" },
    { title: "Go Your Own Way", artist: "Fleetwood Mac", decade: "1970s" },
    { title: "Le Freak", artist: "Chic", decade: "1970s" },
    { title: "Take It Easy", artist: "Eagles", decade: "1970s" },
    { title: "The Chain", artist: "Fleetwood Mac", decade: "1970s" },
    { title: "Roxanne", artist: "The Police", decade: "1970s" },
    { title: "Y.M.C.A.", artist: "Village People", decade: "1970s" },
    { title: "September", artist: "Earth, Wind & Fire", decade: "1970s" },
    { title: "Dancing Queen", artist: "ABBA", decade: "1970s" },
    { title: "Piano Man", artist: "Billy Joel", decade: "1970s" },
    { title: "I Will Survive", artist: "Gloria Gaynor", decade: "1970s" },
    { title: "Play That Funky Music", artist: "Wild Cherry", decade: "1970s" },
    { title: "My Sharona", artist: "The Knack", decade: "1970s" },
    { title: "Don't Stop 'Til You Get Enough", artist: "Michael Jackson", decade: "1970s" },
    { title: "We Are the Champions", artist: "Queen", decade: "1970s" },
    { title: "Rich Girl", artist: "Hall & Oates", decade: "1970s" },
    { title: "War", artist: "Edwin Starr", decade: "1970s" },
    { title: "Baba O'Riley", artist: "The Who", decade: "1970s" },
    { title: "Cat's in the Cradle", artist: "Harry Chapin", decade: "1970s" },
    { title: "Hot Stuff", artist: "Donna Summer", decade: "1970s" },
    { title: "Kung Fu Fighting", artist: "Carl Douglas", decade: "1970s" },
    { title: "You’re So Vain", artist: "Carly Simon", decade: "1970s" },
    { title: "The Boys Are Back in Town", artist: "Thin Lizzy", decade: "1970s" },
    { title: "Born to Run", artist: "Bruce Springsteen", decade: "1970s" },
    { title: "Maggie May", artist: "Rod Stewart", decade: "1970s" },
    { title: "Dreams", artist: "Fleetwood Mac", decade: "1970s" },
    { title: "I Want You to Want Me", artist: "Cheap Trick", decade: "1970s" },
    { title: "Love Hurts", artist: "Nazareth", decade: "1970s" },
    { title: "Blitzkrieg Bop", artist: "Ramones", decade: "1970s" },
    { title: "I Love Rock 'N Roll", artist: "Joan Jett & The Blackhearts", decade: "1970s" },
    { title: "Slow Ride", artist: "Foghat", decade: "1970s" },
    { title: "Landslide", artist: "Fleetwood Mac", decade: "1970s" },
    { title: "Jungle Boogie", artist: "Kool & The Gang", decade: "1970s" },
    { title: "Anarchy in the U.K.", artist: "Sex Pistols", decade: "1970s" },
    { title: "One Way or Another", artist: "Blondie", decade: "1970s" },
    { title: "Take Me Home, Country Roads", artist: "John Denver", decade: "1970s" },
    { title: "Lovin' You", artist: "Minnie Riperton", decade: "1970s" },
    { title: "O-o-h Child", artist: "The Five Stairsteps", decade: "1970s" },
    { title: "Rocket Man", artist: "Elton John", decade: "1970s" },
    { title: "Tiny Dancer", artist: "Elton John", decade: "1970s" },
    { title: "Goodbye Yellow Brick Road", artist: "Elton John", decade: "1970s" },
    { title: "Bennie and the Jets", artist: "Elton John", decade: "1970s" },
    { title: "Sultans of Swing", artist: "Dire Straits", decade: "1970s" },
    { title: "Black Betty", artist: "Ram Jam", decade: "1970s" },
    { title: "Rhiannon", artist: "Fleetwood Mac", decade: "1970s" },
    { title: "You Ain't Seen Nothing Yet", artist: "Bachman-Turner Overdrive", decade: "1970s" },
    { title: "Bang a Gong (Get It On)", artist: "T. Rex", decade: "1970s" },
    { title: "No Woman, No Cry", artist: "Bob Marley & The Wailers", decade: "1970s" },
    { title: "Could You Be Loved", artist: "Bob Marley & The Wailers", decade: "1970s" },
    { title: "Layla", artist: "Derek and the Dominos", decade: "1970s" },
    { title: "Lola", artist: "The Kinks", decade: "1970s" },
    { title: "We’re an American Band", artist: "Grand Funk Railroad", decade: "1970s" },
    { title: "The Joker", artist: "Steve Miller Band", decade: "1970s" },
    { title: "School’s Out", artist: "Alice Cooper", decade: "1970s" },
    { title: "Life in the Fast Lane", artist: "Eagles", decade: "1970s" },
    { title: "Running on Empty", artist: "Jackson Browne", decade: "1970s" },
    { title: "Don't Bring Me Down", artist: "Electric Light Orchestra", decade: "1970s" },
    { title: "Evil Woman", artist: "Electric Light Orchestra", decade: "1970s" },
    { title: "Do It Again", artist: "Steely Dan", decade: "1970s" },
    { title: "Reelin' in the Years", artist: "Steely Dan", decade: "1970s" },
    { title: "Midnight Train to Georgia", artist: "Gladys Knight & The Pips", decade: "1970s" },
    { title: "Knock on Wood", artist: "Amii Stewart", decade: "1970s" },
    { title: "I Want You Back", artist: "The Jackson 5", decade: "1970s" },
    { title: "ABC", artist: "The Jackson 5", decade: "1970s" },
    { title: "You Make Me Feel Like Dancing", artist: "Leo Sayer", decade: "1970s" },
    { title: "Brandy (You're a Fine Girl)", artist: "Looking Glass", decade: "1970s" },
    { title: "Me and Mrs. Jones", artist: "Billy Paul", decade: "1970s" },
    { title: "If You Leave Me Now", artist: "Chicago", decade: "1970s" },
    { title: "You’re the One That I Want", artist: "John Travolta & Olivia Newton-John", decade: "1970s" },
    { title: "Grease", artist: "Frankie Valli", decade: "1970s" },
    { title: "Saturday Night's Alright for Fighting", artist: "Elton John", decade: "1970s" },
    { title: "Love Train", artist: "The O'Jays", decade: "1970s" },
    { title: "If I Can’t Have You", artist: "Yvonne Elliman", decade: "1970s" },
    { title: "Let’s Get It On", artist: "Marvin Gaye", decade: "1970s" },
    { title: "What’s Going On", artist: "Marvin Gaye", decade: "1970s" },
    { title: "Just My Imagination (Running Away with Me)", artist: "The Temptations", decade: "1970s" },
    { title: "Signed, Sealed, Delivered I'm Yours", artist: "Stevie Wonder", decade: "1970s" },
    { title: "Give Up the Funk (Tear the Roof Off the Sucker)", artist: "Parliament", decade: "1970s" },
    { title: "Shining Star", artist: "Earth, Wind & Fire", decade: "1970s" },
    { title: "Float On", artist: "The Floaters", decade: "1970s" },
    { title: "September Morn", artist: "Neil Diamond", decade: "1970s" },
    { title: "I Can See Clearly Now", artist: "Johnny Nash", decade: "1970s" },
    { title: "Baby Don't Forget My Number", artist: "Milli Vanilli", decade: "1970s" },
    { title: "I Just Want to Celebrate", artist: "Rare Earth", decade: "1970s" },
    { title: "Boogie Shoes", artist: "KC & The Sunshine Band", decade: "1970s" },
    { title: "Don't Leave Me This Way", artist: "Thelma Houston", decade: "1970s" },
    { title: "Billie Jean", artist: "Michael Jackson", decade: "1980s" },
  { title: "Take On Me", artist: "a-ha", decade: "1980s" },
  { title: "Sweet Child O' Mine", artist: "Guns N' Roses", decade: "1980s" },
  { title: "Livin' on a Prayer", artist: "Bon Jovi", decade: "1980s" },
  { title: "Like a Virgin", artist: "Madonna", decade: "1980s" },
  { title: "Every Breath You Take", artist: "The Police", decade: "1980s" },
  { title: "With or Without You", artist: "U2", decade: "1980s" },
  { title: "Don't Stop Believin'", artist: "Journey", decade: "1980s" },
  { title: "Africa", artist: "Toto", decade: "1980s" },
  { title: "Wake Me Up Before You Go-Go", artist: "Wham!", decade: "1980s" },
  { title: "Girls Just Want to Have Fun", artist: "Cyndi Lauper", decade: "1980s" },
  { title: "Beat It", artist: "Michael Jackson", decade: "1980s" },
  { title: "Never Gonna Give You Up", artist: "Rick Astley", decade: "1980s" },
  { title: "I Wanna Dance with Somebody", artist: "Whitney Houston", decade: "1980s" },
  { title: "Eye of the Tiger", artist: "Survivor", decade: "1980s" },
  { title: "Here I Go Again", artist: "Whitesnake", decade: "1980s" },
  { title: "You Give Love a Bad Name", artist: "Bon Jovi", decade: "1980s" },
  { title: "Another One Bites the Dust", artist: "Queen", decade: "1980s" },
  { title: "Man in the Mirror", artist: "Michael Jackson", decade: "1980s" },
  { title: "Call Me", artist: "Blondie", decade: "1980s" },
  { title: "Under Pressure", artist: "Queen & David Bowie", decade: "1980s" },
  { title: "Jump", artist: "Van Halen", decade: "1980s" },
  { title: "Sweet Dreams (Are Made of This)", artist: "Eurythmics", decade: "1980s" },
  { title: "Material Girl", artist: "Madonna", decade: "1980s" },
  { title: "The Final Countdown", artist: "Europe", decade: "1980s" },
  { title: "Take My Breath Away", artist: "Berlin", decade: "1980s" },
  { title: "Careless Whisper", artist: "George Michael", decade: "1980s" },
  { title: "Faith", artist: "George Michael", decade: "1980s" },
  { title: "Tainted Love", artist: "Soft Cell", decade: "1980s" },
  { title: "We Built This City", artist: "Starship", decade: "1980s" },
  { title: "Don't You (Forget About Me)", artist: "Simple Minds", decade: "1980s" },
  { title: "Pour Some Sugar on Me", artist: "Def Leppard", decade: "1980s" },
  { title: "Karma Chameleon", artist: "Culture Club", decade: "1980s" },
  { title: "Maneater", artist: "Hall & Oates", decade: "1980s" },
  { title: "Footloose", artist: "Kenny Loggins", decade: "1980s" },
  { title: "Time After Time", artist: "Cyndi Lauper", decade: "1980s" },
  { title: "Total Eclipse of the Heart", artist: "Bonnie Tyler", decade: "1980s" },
  { title: "Don’t Stop the Music", artist: "Yarbrough & Peoples", decade: "1980s" },
  { title: "Let’s Groove", artist: "Earth, Wind & Fire", decade: "1980s" },
  { title: "Walk Like an Egyptian", artist: "The Bangles", decade: "1980s" },
  { title: "Rock You Like a Hurricane", artist: "Scorpions", decade: "1980s" },
  { title: "I Love Rock 'N' Roll", artist: "Joan Jett & The Blackhearts", decade: "1980s" },
  { title: "Funky Town", artist: "Lipps Inc.", decade: "1980s" },
  { title: "Jessie’s Girl", artist: "Rick Springfield", decade: "1980s" },
  { title: "Heaven Is a Place on Earth", artist: "Belinda Carlisle", decade: "1980s" },
  { title: "Venus", artist: "Bananarama", decade: "1980s" },
  { title: "Raspberry Beret", artist: "Prince", decade: "1980s" },
  { title: "Hungry Like the Wolf", artist: "Duran Duran", decade: "1980s" },
  { title: "Everybody Wants to Rule the World", artist: "Tears for Fears", decade: "1980s" },
  { title: "Fast Car", artist: "Tracy Chapman", decade: "1980s" },
  { title: "Invisible Touch", artist: "Genesis", decade: "1980s" },
  { title: "What’s Love Got to Do with It", artist: "Tina Turner", decade: "1980s" },
  { title: "True", artist: "Spandau Ballet", decade: "1980s" },
  { title: "Something About You", artist: "Level 42", decade: "1980s" },
  { title: "Here Comes the Rain Again", artist: "Eurythmics", decade: "1980s" },
  { title: "It's the End of the World as We Know It (And I Feel Fine)", artist: "R.E.M.", decade: "1980s" },
  { title: "She Drives Me Crazy", artist: "Fine Young Cannibals", decade: "1980s" },
  { title: "Owner of a Lonely Heart", artist: "Yes", decade: "1980s" },
  { title: "Shout", artist: "Tears for Fears", decade: "1980s" },
  { title: "One Thing Leads to Another", artist: "The Fixx", decade: "1980s" },
  { title: "Brass in Pocket", artist: "Pretenders", decade: "1980s" },
  { title: "Head Over Heels", artist: "Tears for Fears", decade: "1980s" },
  { title: "The Look", artist: "Roxette", decade: "1980s" },
  { title: "Would I Lie to You?", artist: "Eurythmics", decade: "1980s" },
  { title: "Talk Dirty to Me", artist: "Poison", decade: "1980s" },
  { title: "Love Shack", artist: "The B-52's", decade: "1980s" },
  { title: "I Ran (So Far Away)", artist: "A Flock of Seagulls", decade: "1980s" },
  { title: "Major Tom (Coming Home)", artist: "Peter Schilling", decade: "1980s" },
  { title: "Obsession", artist: "Animotion", decade: "1980s" },
  { title: "Break My Stride", artist: "Matthew Wilder", decade: "1980s" },
  { title: "Let’s Dance", artist: "David Bowie", decade: "1980s" },
  { title: "Don't Forget Me (When I'm Gone)", artist: "Glass Tiger", decade: "1980s" },
  { title: "If You Leave", artist: "Orchestral Manoeuvres in the Dark (OMD)", decade: "1980s" },
  { title: "Chains of Love", artist: "Erasure", decade: "1980s" },
  { title: "West End Girls", artist: "Pet Shop Boys", decade: "1980s" },
  { title: "Died in Your Arms", artist: "Cutting Crew", decade: "1980s" },
  { title: "Safety Dance", artist: "Men Without Hats", decade: "1980s" },
  { title: "I Melt with You", artist: "Modern English", decade: "1980s" },
  { title: "People Are People", artist: "Depeche Mode", decade: "1980s" },
  { title: "This Charming Man", artist: "The Smiths", decade: "1980s" },
  { title: "How Soon Is Now?", artist: "The Smiths", decade: "1980s" },
  { title: "Burning Down the House", artist: "Talking Heads", decade: "1980s" },
  { title: "Genius of Love", artist: "Tom Tom Club", decade: "1980s" },
  { title: "Kiss", artist: "Prince", decade: "1980s" },
  { title: "I Didn’t Mean to Turn You On", artist: "Robert Palmer", decade: "1980s" },
  { title: "Electric Avenue", artist: "Eddy Grant", decade: "1980s" },
  { title: "Private Eyes", artist: "Hall & Oates", decade: "1980s" },
  { title: "She Works Hard for the Money", artist: "Donna Summer", decade: "1980s" },
  { title: "Two of Hearts", artist: "Stacey Q", decade: "1980s" },
  { title: "Come On Eileen", artist: "Dexys Midnight Runners", decade: "1980s" },
  { title: "Sister Christian", artist: "Night Ranger", decade: "1980s" },
  { title: "Love Bites", artist: "Def Leppard", decade: "1980s" },
  { title: "Tempted", artist: "Squeeze", decade: "1980s" },
  { title: "Steppin' Out", artist: "Joe Jackson", decade: "1980s" },
  { title: "In a Big Country", artist: "Big Country", decade: "1980s" },
  { title: "Send Me an Angel", artist: "Real Life", decade: "1980s" },
  { title: "Do You Really Want to Hurt Me", artist: "Culture Club", decade: "1980s" },
  { title: "Smells Like Teen Spirit", artist: "Nirvana", decade: "1990s" },
  { title: "Wonderwall", artist: "Oasis", decade: "1990s" },
  { title: "I Want It That Way", artist: "Backstreet Boys", decade: "1990s" },
  { title: "Losing My Religion", artist: "R.E.M.", decade: "1990s" },
  { title: "Torn", artist: "Natalie Imbruglia", decade: "1990s" },
  { title: "My Heart Will Go On", artist: "Celine Dion", decade: "1990s" },
  { title: "Baby One More Time", artist: "Britney Spears", decade: "1990s" },
  { title: "Wannabe", artist: "Spice Girls", decade: "1990s" },
  { title: "Black Hole Sun", artist: "Soundgarden", decade: "1990s" },
  { title: "Enter Sandman", artist: "Metallica", decade: "1990s" },
  { title: "I Will Always Love You", artist: "Whitney Houston", decade: "1990s" },
  { title: "No Scrubs", artist: "TLC", decade: "1990s" },
  { title: "I Don't Want to Miss a Thing", artist: "Aerosmith", decade: "1990s" },
  { title: "Killing Me Softly", artist: "Fugees", decade: "1990s" },
  { title: "Livin' la Vida Loca", artist: "Ricky Martin", decade: "1990s" },
  { title: "Barbie Girl", artist: "Aqua", decade: "1990s" },
  { title: "Tearin' Up My Heart", artist: "NSYNC", decade: "1990s" },
  { title: "Iris", artist: "Goo Goo Dolls", decade: "1990s" },
  { title: "Say My Name", artist: "Destiny's Child", decade: "1990s" },
  { title: "All Star", artist: "Smash Mouth", decade: "1990s" },
  { title: "Semi-Charmed Life", artist: "Third Eye Blind", decade: "1990s" },
  { title: "You Get What You Give", artist: "New Radicals", decade: "1990s" },
  { title: "Jump Around", artist: "House of Pain", decade: "1990s" },
  { title: "Tubthumping", artist: "Chumbawamba", decade: "1990s" },
  { title: "Waterfalls", artist: "TLC", decade: "1990s" },
  { title: "Don't Speak", artist: "No Doubt", decade: "1990s" },
  { title: "More Than Words", artist: "Extreme", decade: "1990s" },
  { title: "Creep", artist: "Radiohead", decade: "1990s" },
  { title: "Bittersweet Symphony", artist: "The Verve", decade: "1990s" },
  { title: "Macarena", artist: "Los Del Rio", decade: "1990s" },
  { title: "Basket Case", artist: "Green Day", decade: "1990s" },
  { title: "Good Riddance (Time of Your Life)", artist: "Green Day", decade: "1990s" },
  { title: "The Sign", artist: "Ace of Base", decade: "1990s" },
  { title: "Genie in a Bottle", artist: "Christina Aguilera", decade: "1990s" },
  { title: "Believe", artist: "Cher", decade: "1990s" },
  { title: "Closing Time", artist: "Semisonic", decade: "1990s" },
  { title: "Tennessee", artist: "Arrested Development", decade: "1990s" },
  { title: "No Diggity", artist: "Blackstreet ft. Dr. Dre & Queen Pen", decade: "1990s" },
  { title: "Virtual Insanity", artist: "Jamiroquai", decade: "1990s" },
  { title: "Only Wanna Be with You", artist: "Hootie & The Blowfish", decade: "1990s" },
  { title: "Smooth", artist: "Santana ft. Rob Thomas", decade: "1990s" },
  { title: "Under the Bridge", artist: "Red Hot Chili Peppers", decade: "1990s" },
  { title: "Two Princes", artist: "Spin Doctors", decade: "1990s" },
  { title: "Give It Away", artist: "Red Hot Chili Peppers", decade: "1990s" },
  { title: "My Own Worst Enemy", artist: "Lit", decade: "1990s" },
  { title: "Steal My Sunshine", artist: "Len", decade: "1990s" },
  { title: "Glycerine", artist: "Bush", decade: "1990s" },
  { title: "Lullaby", artist: "Shawn Mullins", decade: "1990s" },
  { title: "I'll Be", artist: "Edwin McCain", decade: "1990s" },
  { title: "Everlong", artist: "Foo Fighters", decade: "1990s" },
  { title: "Jeremy", artist: "Pearl Jam", decade: "1990s" },
  { title: "Interstate Love Song", artist: "Stone Temple Pilots", decade: "1990s" },
  { title: "Sex and Candy", artist: "Marcy Playground", decade: "1990s" },
  { title: "Santa Monica", artist: "Everclear", decade: "1990s" },
  { title: "Inside Out", artist: "Eve 6", decade: "1990s" },
  { title: "Slide", artist: "Goo Goo Dolls", decade: "1990s" },
  { title: "Hey Jealousy", artist: "Gin Blossoms", decade: "1990s" },
  { title: "Run-Around", artist: "Blues Traveler", decade: "1990s" },
  { title: "Shimmer", artist: "Fuel", decade: "1990s" },
  { title: "Are You Gonna Go My Way", artist: "Lenny Kravitz", decade: "1990s" },
  { title: "Bound for the Floor", artist: "Local H", decade: "1990s" },
  { title: "What It's Like", artist: "Everlast", decade: "1990s" },
  { title: "You Were Meant for Me", artist: "Jewel", decade: "1990s" },
  { title: "Sunny Came Home", artist: "Shawn Colvin", decade: "1990s" },
  { title: "The Way", artist: "Fastball", decade: "1990s" },
  { title: "You Oughta Know", artist: "Alanis Morissette", decade: "1990s" },
  { title: "Hand in My Pocket", artist: "Alanis Morissette", decade: "1990s" },
  { title: "Building a Mystery", artist: "Sarah McLachlan", decade: "1990s" },
  { title: "Linger", artist: "The Cranberries", decade: "1990s" },
  { title: "Zombie", artist: "The Cranberries", decade: "1990s" },
  { title: "I Don't Want to Wait", artist: "Paula Cole", decade: "1990s" },
  { title: "Missing", artist: "Everything but the Girl", decade: "1990s" },
  { title: "Damn I Wish I Was Your Lover", artist: "Sophie B. Hawkins", decade: "1990s" },
  { title: "Lovefool", artist: "The Cardigans", decade: "1990s" },
  { title: "Kiss Me", artist: "Sixpence None the Richer", decade: "1990s" },
  { title: "Torn", artist: "Natalie Imbruglia", decade: "1990s" },
  { title: "Where Have All the Cowboys Gone?", artist: "Paula Cole", decade: "1990s" },
  { title: "No Rain", artist: "Blind Melon", decade: "1990s" },
  { title: "She Talks to Angels", artist: "The Black Crowes", decade: "1990s" },
  { title: "Plush", artist: "Stone Temple Pilots", decade: "1990s" },
  { title: "Man on the Moon", artist: "R.E.M.", decade: "1990s" },
  { title: "If It Makes You Happy", artist: "Sheryl Crow", decade: "1990s" },
  { title: "All I Wanna Do", artist: "Sheryl Crow", decade: "1990s" },
  { title: "Fly", artist: "Sugar Ray", decade: "1990s" },
  { title: "Someday", artist: "Sugar Ray", decade: "1990s" },
  { title: "Absolutely (Story of a Girl)", artist: "Nine Days", decade: "1990s" },
  { title: "Meet Virginia", artist: "Train", decade: "1990s" },
  { title: "Closing Time", artist: "Semisonic", decade: "1990s" },
  { title: "Criminal", artist: "Fiona Apple", decade: "1990s" },
  { title: "Bitch", artist: "Meredith Brooks", decade: "1990s" },
  { title: "Fast as You", artist: "Dwight Yoakam", decade: "1990s" },
  { title: "This Kiss", artist: "Faith Hill", decade: "1990s" },
  { title: "Man! I Feel Like a Woman!", artist: "Shania Twain", decade: "1990s" },
  { title: "Any Man of Mine", artist: "Shania Twain", decade: "1990s" },
  { title: "The Dance", artist: "Garth Brooks", decade: "1990s" },
  { title: "Friends in Low Places", artist: "Garth Brooks", decade: "1990s" },
  { title: "Strawberry Wine", artist: "Deana Carter", decade: "1990s" },
  { title: "How Do I Live", artist: "LeAnn Rimes", decade: "1990s" },
  { title: "MMMBop", artist: "Hanson", decade: "1990s" },
  { title: "She's So High", artist: "Tal Bachman", decade: "1990s" },
  { title: "Unpretty", artist: "TLC", decade: "1990s" },
  { title: "Give Me One Reason", artist: "Tracy Chapman", decade: "1990s" },
  { title: "Only Wanna Be with You", artist: "Hootie & The Blowfish", decade: "1990s" },
  { title: "Let Her Cry", artist: "Hootie & The Blowfish", decade: "1990s" },
  { title: "Stay", artist: "Lisa Loeb & Nine Stories", decade: "1990s" },
  { title: "What I Got", artist: "Sublime", decade: "1990s" },
  { title: "Santeria", artist: "Sublime", decade: "1990s" },
  { title: "Where It’s At", artist: "Beck", decade: "1990s" },
  { title: "Loser", artist: "Beck", decade: "1990s" },
  { title: "Learn to Fly", artist: "Foo Fighters", decade: "1990s" },
  { title: "One", artist: "U2", decade: "1990s" },
  { title: "Even Flow", artist: "Pearl Jam", decade: "1990s" },
  { title: "Self Esteem", artist: "The Offspring", decade: "1990s" },
  { title: "My Friends", artist: "Red Hot Chili Peppers", decade: "1990s" },
  { title: "Santa Monica", artist: "Everclear", decade: "1990s" },
  { title: "All I Want", artist: "Toad the Wet Sprocket", decade: "1990s" },
  { title: "Counting Blue Cars", artist: "Dishwalla", decade: "1990s" },
  { title: "Closing Time", artist: "Semisonic", decade: "1990s" },
  { title: "Crush", artist: "Dave Matthews Band", decade: "1990s" },
  { title: "Ants Marching", artist: "Dave Matthews Band", decade: "1990s" },
  { title: "Follow You Down", artist: "Gin Blossoms", decade: "1990s" },
  { title: "Name", artist: "Goo Goo Dolls", decade: "1990s" },
  { title: "Back for Good", artist: "Take That", decade: "1990s" },
  { title: "The Freshmen", artist: "The Verve Pipe", decade: "1990s" },
  { title: "I Love You Always Forever", artist: "Donna Lewis", decade: "1990s" },
  { title: "Runaway Train", artist: "Soul Asylum", decade: "1990s" },
  { title: "Nothing Compares 2 U", artist: "Sinéad O'Connor", decade: "1990s" },
  { title: "Fade Into You", artist: "Mazzy Star", decade: "1990s" },
  { title: "Ray of Light", artist: "Madonna", decade: "1990s" },
  { title: "Frozen", artist: "Madonna", decade: "1990s" },
  { title: "Jump", artist: "Kriss Kross", decade: "1990s" },
  { title: "Parents Just Don't Understand", artist: "DJ Jazzy Jeff & The Fresh Prince", decade: "1990s" },
  { title: "U Can't Touch This", artist: "MC Hammer", decade: "1990s" },
  { title: "O.P.P.", artist: "Naughty by Nature", decade: "1990s" },
  { title: "C.R.E.A.M.", artist: "Wu-Tang Clan", decade: "1990s" },
  { title: "Big Poppa", artist: "The Notorious B.I.G.", decade: "1990s" },
  { title: "Mo Money Mo Problems", artist: "The Notorious B.I.G. ft. Mase & Puff Daddy", decade: "1990s" },
  { title: "California Love", artist: "2Pac ft. Dr. Dre", decade: "1990s" },
  { title: "My Name Is", artist: "Eminem", decade: "1990s" },
  { title: "Nuthin' but a 'G' Thang", artist: "Dr. Dre ft. Snoop Doggy Dogg", decade: "1990s" },
  { title: "I Got 5 on It", artist: "Luniz", decade: "1990s" },
  { title: "Regulate", artist: "Warren G & Nate Dogg", decade: "1990s" },
  { title: "The Boy Is Mine", artist: "Brandy & Monica", decade: "1990s" },
  { title: "No Ordinary Love", artist: "Sade", decade: "1990s" },
  { title: "You're Still the One", artist: "Shania Twain", decade: "1990s" },
  { title: "Achy Breaky Heart", artist: "Billy Ray Cyrus", decade: "1990s" },
  { title: "Something Like That", artist: "Tim McGraw", decade: "1990s" },
  { title: "Yeah!", artist: "Usher ft. Lil Jon & Ludacris", decade: "2000s" },
  { title: "Since U Been Gone", artist: "Kelly Clarkson", decade: "2000s" },
  { title: "In Da Club", artist: "50 Cent", decade: "2000s" },
  { title: "Mr. Brightside", artist: "The Killers", decade: "2000s" },
  { title: "Seven Nation Army", artist: "The White Stripes", decade: "2000s" },
  { title: "Hot in Herre", artist: "Nelly", decade: "2000s" },
  { title: "Crazy in Love", artist: "Beyoncé ft. Jay-Z", decade: "2000s" },
  { title: "Hips Don't Lie", artist: "Shakira ft. Wyclef Jean", decade: "2000s" },
  { title: "Gold Digger", artist: "Kanye West ft. Jamie Foxx", decade: "2000s" },
  { title: "Bring Me to Life", artist: "Evanescence", decade: "2000s" },
  { title: "Complicated", artist: "Avril Lavigne", decade: "2000s" },
  { title: "Sk8er Boi", artist: "Avril Lavigne", decade: "2000s" },
  { title: "Uptown Girl", artist: "Westlife", decade: "2000s" },
  { title: "A Thousand Miles", artist: "Vanessa Carlton", decade: "2000s" },
  { title: "Toxic", artist: "Britney Spears", decade: "2000s" },
  { title: "Oops!... I Did It Again", artist: "Britney Spears", decade: "2000s" },
  { title: "Bye Bye Bye", artist: "NSYNC", decade: "2000s" },
  { title: "I Want It That Way", artist: "Backstreet Boys", decade: "2000s" },
  { title: "Poker Face", artist: "Lady Gaga", decade: "2000s" },
  { title: "Just Dance", artist: "Lady Gaga ft. Colby O’Donis", decade: "2000s" },
  { title: "Drop It Like It’s Hot", artist: "Snoop Dogg ft. Pharrell", decade: "2000s" },
  { title: "Beautiful Day", artist: "U2", decade: "2000s" },
  { title: "Viva La Vida", artist: "Coldplay", decade: "2000s" },
  { title: "Clocks", artist: "Coldplay", decade: "2000s" },
  { title: "Hey There Delilah", artist: "Plain White T's", decade: "2000s" },
  { title: "You're Beautiful", artist: "James Blunt", decade: "2000s" },
  { title: "Hollaback Girl", artist: "Gwen Stefani", decade: "2000s" },
  { title: "Milkshake", artist: "Kelis", decade: "2000s" },
  { title: "Temperature", artist: "Sean Paul", decade: "2000s" },
  { title: "Let Me Love You", artist: "Mario", decade: "2000s" },
  { title: "Bleeding Love", artist: "Leona Lewis", decade: "2000s" },
  { title: "Before He Cheats", artist: "Carrie Underwood", decade: "2000s" },
  { title: "Big Girls Don't Cry", artist: "Fergie", decade: "2000s" },
  { title: "Where Is the Love?", artist: "Black Eyed Peas", decade: "2000s" },
  { title: "I Gotta Feeling", artist: "Black Eyed Peas", decade: "2000s" },
  { title: "Boulevard of Broken Dreams", artist: "Green Day", decade: "2000s" },
  { title: "American Idiot", artist: "Green Day", decade: "2000s" },
  { title: "How to Save a Life", artist: "The Fray", decade: "2000s" },
  { title: "Over My Head (Cable Car)", artist: "The Fray", decade: "2000s" },
  { title: "Crazy", artist: "Gnarls Barkley", decade: "2000s" },
  { title: "Rehab", artist: "Amy Winehouse", decade: "2000s" },
  { title: "I Kissed a Girl", artist: "Katy Perry", decade: "2000s" },
  { title: "Hot N Cold", artist: "Katy Perry", decade: "2000s" },
  { title: "Cry Me a River", artist: "Justin Timberlake", decade: "2000s" },
  { title: "SexyBack", artist: "Justin Timberlake", decade: "2000s" },
  { title: "Cry", artist: "Mandy Moore", decade: "2000s" },
  { title: "Unwritten", artist: "Natasha Bedingfield", decade: "2000s" },
  { title: "Bad Day", artist: "Daniel Powter", decade: "2000s" },
  { title: "No One", artist: "Alicia Keys", decade: "2000s" },
  { title: "Fallin'", artist: "Alicia Keys", decade: "2000s" },
  { title: "My Happy Ending", artist: "Avril Lavigne", decade: "2000s" },
  { title: "Pieces of Me", artist: "Ashlee Simpson", decade: "2000s" },
  { title: "Leave (Get Out)", artist: "JoJo", decade: "2000s" },
  { title: "We Belong Together", artist: "Mariah Carey", decade: "2000s" },
  { title: "Don't Forget About Us", artist: "Mariah Carey", decade: "2000s" },
  { title: "So Sick", artist: "Ne-Yo", decade: "2000s" },
  { title: "Beautiful Soul", artist: "Jesse McCartney", decade: "2000s" },
  { title: "Because of You", artist: "Kelly Clarkson", decade: "2000s" },
  { title: "Breakaway", artist: "Kelly Clarkson", decade: "2000s" },
  { title: "Stronger", artist: "Kanye West", decade: "2000s" },
  { title: "Jesus Walks", artist: "Kanye West", decade: "2000s" },
  { title: "Slow Jamz", artist: "Twista ft. Kanye West & Jamie Foxx", decade: "2000s" },
  { title: "Over and Over", artist: "Nelly ft. Tim McGraw", decade: "2000s" },
  { title: "Buy U a Drank (Shawty Snappin’)", artist: "T-Pain ft. Yung Joc", decade: "2000s" },
  { title: "Bartender", artist: "T-Pain ft. Akon", decade: "2000s" },
  { title: "Low", artist: "Flo Rida ft. T-Pain", decade: "2000s" },
  { title: "Shake It", artist: "Metro Station", decade: "2000s" },
  { title: "Check Yes Juliet", artist: "We The Kings", decade: "2000s" },
  { title: "Teenagers", artist: "My Chemical Romance", decade: "2000s" },
  { title: "Helena", artist: "My Chemical Romance", decade: "2000s" },
  { title: "Dance, Dance", artist: "Fall Out Boy", decade: "2000s" },
  { title: "Thnks fr th Mmrs", artist: "Fall Out Boy", decade: "2000s" },
  { title: "Face Down", artist: "The Red Jumpsuit Apparatus", decade: "2000s" },
  { title: "Sugar, We're Goin Down", artist: "Fall Out Boy", decade: "2000s" },
  { title: "Dirty Little Secret", artist: "The All-American Rejects", decade: "2000s" },
  { title: "Gives You Hell", artist: "The All-American Rejects", decade: "2000s" },
  { title: "Misery Business", artist: "Paramore", decade: "2000s" },
  { title: "Decode", artist: "Paramore", decade: "2000s" },
  { title: "Ocean Avenue", artist: "Yellowcard", decade: "2000s" },
  { title: "Here (In Your Arms)", artist: "Hellogoodbye", decade: "2000s" },
  { title: "Lips of an Angel", artist: "Hinder", decade: "2000s" },
  { title: "It’s Not Over", artist: "Daughtry", decade: "2000s" },
  { title: "Home", artist: "Daughtry", decade: "2000s" },
  { title: "She Will Be Loved", artist: "Maroon 5", decade: "2000s" },
  { title: "This Love", artist: "Maroon 5", decade: "2000s" },
  { title: "Sunday Morning", artist: "Maroon 5", decade: "2000s" },
  { title: "I Write Sins Not Tragedies", artist: "Panic! At The Disco", decade: "2000s" },
  { title: "Nine in the Afternoon", artist: "Panic! At The Disco", decade: "2000s" },
  { title: "Bubbly", artist: "Colbie Caillat", decade: "2000s" },
  { title: "Realize", artist: "Colbie Caillat", decade: "2000s" },
  { title: "Love Song", artist: "Sara Bareilles", decade: "2000s" },
  { title: "Pocketful of Sunshine", artist: "Natasha Bedingfield", decade: "2000s" },
  { title: "Who Knew", artist: "Pink", decade: "2000s" },
  { title: "Just Like a Pill", artist: "Pink", decade: "2000s" },
  { title: "So What", artist: "Pink", decade: "2000s" },
  { title: "Better in Time", artist: "Leona Lewis", decade: "2000s" },
  { title: "Tattoo", artist: "Jordin Sparks", decade: "2000s" },
  { title: "Hey Ya!", artist: "OutKast", decade: "2000s" },
  { title: "Roses", artist: "OutKast", decade: "2000s" },
  { title: "Lose Yourself", artist: "Eminem", decade: "2000s" },
  { title: "Without Me", artist: "Eminem", decade: "2000s" },
  { title: "Stan", artist: "Eminem ft. Dido", decade: "2000s" },
  { title: "My Band", artist: "D12", decade: "2000s" },
  { title: "Lollipop", artist: "Lil Wayne ft. Static Major", decade: "2000s" },
  { title: "A Milli", artist: "Lil Wayne", decade: "2000s" },
  { title: "Work It", artist: "Missy Elliott", decade: "2000s" },
  { title: "Get Ur Freak On", artist: "Missy Elliott", decade: "2000s" },
  { title: "My Boo", artist: "Usher & Alicia Keys", decade: "2000s" },
  { title: "Burn", artist: "Usher", decade: "2000s" },
  { title: "Let It Burn", artist: "Usher", decade: "2000s" },
  { title: "Lonely", artist: "Akon", decade: "2000s" },
  { title: "Right Now (Na Na Na)", artist: "Akon", decade: "2000s" },
  { title: "We Takin' Over", artist: "DJ Khaled ft. Akon, T.I., Lil Wayne, Rick Ross", decade: "2000s" },
  { title: "Cyclone", artist: "Baby Bash ft. T-Pain", decade: "2000s" },
  { title: "Bartender", artist: "T-Pain ft. Akon", decade: "2000s" },
  { title: "Whatever You Like", artist: "T.I.", decade: "2000s" },
  { title: "Live Your Life", artist: "T.I. ft. Rihanna", decade: "2000s" },
  { title: "Disturbia", artist: "Rihanna", decade: "2000s" },
  { title: "SOS", artist: "Rihanna", decade: "2000s" },
  { title: "Hate That I Love You", artist: "Rihanna ft. Ne-Yo", decade: "2000s" },
  { title: "Take a Bow", artist: "Rihanna", decade: "2000s" },
  { title: "Sexy Love", artist: "Ne-Yo", decade: "2000s" },
  { title: "Miss Independent", artist: "Ne-Yo", decade: "2000s" },
  { title: "Promiscuous", artist: "Nelly Furtado ft. Timbaland", decade: "2000s" },
  { title: "Say It Right", artist: "Nelly Furtado", decade: "2000s" },
  { title: "Maneater", artist: "Nelly Furtado", decade: "2000s" },
  { title: "Love in This Club", artist: "Usher ft. Young Jeezy", decade: "2000s" },
  { title: "Buy Me a Rose", artist: "Luther Vandross", decade: "2000s" },
  { title: "You're Gonna Go Far, Kid", artist: "The Offspring", decade: "2000s" },
  { title: "Paralyzer", artist: "Finger Eleven", decade: "2000s" },
  { title: "Check On It", artist: "Beyoncé ft. Slim Thug", decade: "2000s" },
  { title: "Beautiful", artist: "Christina Aguilera", decade: "2000s" },
  { title: "Dirrty", artist: "Christina Aguilera ft. Redman", decade: "2000s" },
  { title: "Fighter", artist: "Christina Aguilera", decade: "2000s" },
  { title: "Stacy's Mom", artist: "Fountains of Wayne", decade: "2000s" },
  { title: "Drops of Jupiter", artist: "Train", decade: "2000s" },
  { title: "Meet Virginia", artist: "Train", decade: "2000s" },
  { title: "All the Things She Said", artist: "t.A.T.u.", decade: "2000s" },
  { title: "It's My Life", artist: "Bon Jovi", decade: "2000s" },
  { title: "She Hates Me", artist: "Puddle of Mudd", decade: "2000s" },
  { title: "How You Remind Me", artist: "Nickelback", decade: "2000s" },
  { title: "Photograph", artist: "Nickelback", decade: "2000s" },
  { title: "Here Without You", artist: "3 Doors Down", decade: "2000s" },
  { title: "Kryptonite", artist: "3 Doors Down", decade: "2000s" },
  { title: "Lips of an Angel", artist: "Hinder", decade: "2000s" },
  { title: "All Star", artist: "Smash Mouth", decade: "2000s" },
  { title: "Absolutely (Story of a Girl)", artist: "Nine Days", decade: "2000s" },
{ title: "Hanging by a Moment", artist: "Lifehouse", decade: "2000s" },
{ title: "You and Me", artist: "Lifehouse", decade: "2000s" },
{ title: "Far Away", artist: "Nickelback", decade: "2000s" },
{ title: "Someday", artist: "Nickelback", decade: "2000s" },
{ title: "Save Tonight", artist: "Eagle-Eye Cherry", decade: "2000s" },
{ title: "If You’re Gone", artist: "Matchbox Twenty", decade: "2000s" },
{ title: "Bent", artist: "Matchbox Twenty", decade: "2000s" },
{ title: "Let Me Go", artist: "Three Doors Down", decade: "2000s" },
{ title: "Here It Goes Again", artist: "OK Go", decade: "2000s" },
{ title: "Vindicated", artist: "Dashboard Confessional", decade: "2000s" },
{ title: "Screaming Infidelities", artist: "Dashboard Confessional", decade: "2000s" },
{ title: "Take Me Out", artist: "Franz Ferdinand", decade: "2000s" },
{ title: "Somebody Told Me", artist: "The Killers", decade: "2000s" },
{ title: "Maps", artist: "Yeah Yeah Yeahs", decade: "2000s" },
{ title: "The Middle", artist: "Jimmy Eat World", decade: "2000s" },
{ title: "Sweet Disposition", artist: "The Temper Trap", decade: "2000s" },
{ title: "Chasing Cars", artist: "Snow Patrol", decade: "2000s" },
{ title: "Run", artist: "Snow Patrol", decade: "2000s" },
{ title: "Stop and Stare", artist: "OneRepublic", decade: "2000s" },
{ title: "Apologize", artist: "Timbaland ft. OneRepublic", decade: "2000s" },
{ title: "Bleed It Out", artist: "Linkin Park", decade: "2000s" },
{ title: "Breaking the Habit", artist: "Linkin Park", decade: "2000s" },
{ title: "Crawling", artist: "Linkin Park", decade: "2000s" },
{ title: "Wake Me Up When September Ends", artist: "Green Day", decade: "2000s" },
{ title: "Shadow of the Day", artist: "Linkin Park", decade: "2000s" },
{ title: "In Too Deep", artist: "Sum 41", decade: "2000s" },
{ title: "Fat Lip", artist: "Sum 41", decade: "2000s" },
{ title: "Blurry", artist: "Puddle of Mudd", decade: "2000s" },
{ title: "Everything You Want", artist: "Vertical Horizon", decade: "2000s" },
{ title: "Unwell", artist: "Matchbox Twenty", decade: "2000s" },
{ title: "How Far We’ve Come", artist: "Matchbox Twenty", decade: "2000s" },
{ title: "Kiss Kiss", artist: "Chris Brown ft. T-Pain", decade: "2000s" },
{ title: "Run It!", artist: "Chris Brown", decade: "2000s" },
{ title: "Like I Love You", artist: "Justin Timberlake", decade: "2000s" },
{ title: "Can’t Hold Us Down", artist: "Christina Aguilera ft. Lil’ Kim", decade: "2000s" },
{ title: "1, 2 Step", artist: "Ciara ft. Missy Elliott", decade: "2000s" },
{ title: "Goodies", artist: "Ciara ft. Petey Pablo", decade: "2000s" },
{ title: "Ride", artist: "Ciara ft. Ludacris", decade: "2000s" },
{ title: "Love Don’t Cost a Thing", artist: "Jennifer Lopez", decade: "2000s" },
{ title: "Jenny from the Block", artist: "Jennifer Lopez", decade: "2000s" },
{ title: "Waiting for Tonight", artist: "Jennifer Lopez", decade: "2000s" },
{ title: "Whenever, Wherever", artist: "Shakira", decade: "2000s" },
{ title: "Objection (Tango)", artist: "Shakira", decade: "2000s" },
{ title: "Suga Suga", artist: "Baby Bash ft. Frankie J", decade: "2000s" },
{ title: "Lean Back", artist: "Terror Squad ft. Fat Joe & Remy Ma", decade: "2000s" },
{ title: "Where’d You Go", artist: "Fort Minor", decade: "2000s" },
{ title: "Remember the Name", artist: "Fort Minor", decade: "2000s" },
{ title: "Temperature", artist: "Sean Paul", decade: "2000s" },
{ title: "We Be Burnin'", artist: "Sean Paul", decade: "2000s" },
  { title: "Rolling in the Deep", artist: "Adele", decade: "2010s" },
  { title: "Someone Like You", artist: "Adele", decade: "2010s" },
  { title: "Hello", artist: "Adele", decade: "2010s" },
  { title: "Uptown Funk", artist: "Mark Ronson ft. Bruno Mars", decade: "2010s" },
  { title: "Locked Out of Heaven", artist: "Bruno Mars", decade: "2010s" },
  { title: "24K Magic", artist: "Bruno Mars", decade: "2010s" },
  { title: "Grenade", artist: "Bruno Mars", decade: "2010s" },
  { title: "Roar", artist: "Katy Perry", decade: "2010s" },
  { title: "Dark Horse", artist: "Katy Perry ft. Juicy J", decade: "2010s" },
  { title: "Teenage Dream", artist: "Katy Perry", decade: "2010s" },
  { title: "We Are Never Ever Getting Back Together", artist: "Taylor Swift", decade: "2010s" },
  { title: "Shake It Off", artist: "Taylor Swift", decade: "2010s" },
  { title: "Blank Space", artist: "Taylor Swift", decade: "2010s" },
  { title: "Lover", artist: "Taylor Swift", decade: "2010s" },
  { title: "Bad Guy", artist: "Billie Eilish", decade: "2010s" },
  { title: "Everything I Wanted", artist: "Billie Eilish", decade: "2010s" },
  { title: "Happier Than Ever", artist: "Billie Eilish", decade: "2010s" },
  { title: "Can't Stop the Feeling!", artist: "Justin Timberlake", decade: "2010s" },
  { title: "Mirrors", artist: "Justin Timberlake", decade: "2010s" },
  { title: "Love Me Like You Do", artist: "Ellie Goulding", decade: "2010s" },
  { title: "Lights", artist: "Ellie Goulding", decade: "2010s" },
  { title: "Stay With Me", artist: "Sam Smith", decade: "2010s" },
  { title: "Too Good at Goodbyes", artist: "Sam Smith", decade: "2010s" },
  { title: "What Do You Mean?", artist: "Justin Bieber", decade: "2010s" },
  { title: "Love Yourself", artist: "Justin Bieber", decade: "2010s" },
  { title: "Sorry", artist: "Justin Bieber", decade: "2010s" },
  { title: "Despacito", artist: "Luis Fonsi ft. Daddy Yankee", decade: "2010s" },
  { title: "Taki Taki", artist: "DJ Snake ft. Selena Gomez, Ozuna, Cardi B", decade: "2010s" },
  { title: "Señorita", artist: "Shawn Mendes & Camila Cabello", decade: "2010s" },
  { title: "Havana", artist: "Camila Cabello ft. Young Thug", decade: "2010s" },
  { title: "The Middle", artist: "Zedd, Maren Morris & Grey", decade: "2010s" },
  { title: "Closer", artist: "The Chainsmokers ft. Halsey", decade: "2010s" },
  { title: "Don't Let Me Down", artist: "The Chainsmokers ft. Daya", decade: "2010s" },
  { title: "High Hopes", artist: "Panic! At The Disco", decade: "2010s" },
  { title: "Hey Look Ma, I Made It", artist: "Panic! At The Disco", decade: "2010s" },
  { title: "Radioactive", artist: "Imagine Dragons", decade: "2010s" },
  { title: "Demons", artist: "Imagine Dragons", decade: "2010s" },
  { title: "Thunder", artist: "Imagine Dragons", decade: "2010s" },
  { title: "Counting Stars", artist: "OneRepublic", decade: "2010s" },
  { title: "Apologize", artist: "Timbaland ft. OneRepublic", decade: "2010s" },
  { title: "Royals", artist: "Lorde", decade: "2010s" },
  { title: "Green Light", artist: "Lorde", decade: "2010s" },
  { title: "We Found Love", artist: "Rihanna ft. Calvin Harris", decade: "2010s" },
  { title: "Diamonds", artist: "Rihanna", decade: "2010s" },
  { title: "Uptown Girl", artist: "Westlife", decade: "2010s" },
  { title: "Timber", artist: "Pitbull ft. Kesha", decade: "2010s" },
  { title: "All of Me", artist: "John Legend", decade: "2010s" },
  { title: "Rude", artist: "MAGIC!", decade: "2010s" },
  { title: "Shape of You", artist: "Ed Sheeran", decade: "2010s" },
  { title: "Thinking Out Loud", artist: "Ed Sheeran", decade: "2010s" },
  { title: "Perfect", artist: "Ed Sheeran", decade: "2010s" },
  { title: "Photograph", artist: "Ed Sheeran", decade: "2010s" },
  { title: "Work", artist: "Rihanna ft. Drake", decade: "2010s" },
  { title: "Needed Me", artist: "Rihanna", decade: "2010s" },
  { title: "Lush Life", artist: "Zara Larsson", decade: "2010s" },
  { title: "Symphony", artist: "Clean Bandit ft. Zara Larsson", decade: "2010s" },
  { title: "Rather Be", artist: "Clean Bandit ft. Jess Glynne", decade: "2010s" },
  { title: "Take Me to Church", artist: "Hozier", decade: "2010s" },
  { title: "Somebody That I Used to Know", artist: "Gotye ft. Kimbra", decade: "2010s" },
  { title: "Pumped Up Kicks", artist: "Foster the People", decade: "2010s" },
  { title: "Ride", artist: "Twenty One Pilots", decade: "2010s" },
  { title: "Stressed Out", artist: "Twenty One Pilots", decade: "2010s" },
  { title: "Heathens", artist: "Twenty One Pilots", decade: "2010s" },
  { title: "We Can't Stop", artist: "Miley Cyrus", decade: "2010s" },
  { title: "Wrecking Ball", artist: "Miley Cyrus", decade: "2010s" },
  { title: "Party in the U.S.A.", artist: "Miley Cyrus", decade: "2010s" },
  { title: "No Tears Left to Cry", artist: "Ariana Grande", decade: "2010s" },
  { title: "Side to Side", artist: "Ariana Grande ft. Nicki Minaj", decade: "2010s" },
  { title: "Break Free", artist: "Ariana Grande ft. Zedd", decade: "2010s" },
  { title: "Bang Bang", artist: "Jessie J, Ariana Grande, Nicki Minaj", decade: "2010s" },
  { title: "Me Too", artist: "Meghan Trainor", decade: "2010s" },
  { title: "All About That Bass", artist: "Meghan Trainor", decade: "2010s" },
  { title: "NO", artist: "Meghan Trainor", decade: "2010s" },
  { title: "Fancy", artist: "Iggy Azalea ft. Charli XCX", decade: "2010s" },
  { title: "Boom Clap", artist: "Charli XCX", decade: "2010s" },
  { title: "I Love It", artist: "Icona Pop ft. Charli XCX", decade: "2010s" },
  { title: "Stay", artist: "Zedd & Alessia Cara", decade: "2010s" },
  { title: "Here", artist: "Alessia Cara", decade: "2010s" },
  { title: "Scars to Your Beautiful", artist: "Alessia Cara", decade: "2010s" },
  { title: "Work from Home", artist: "Fifth Harmony ft. Ty Dolla $ign", decade: "2010s" },
  { title: "Sledgehammer", artist: "Fifth Harmony", decade: "2010s" },
  { title: "Dynamite", artist: "Taio Cruz", decade: "2010s" },
  { title: "Replay", artist: "Iyaz", decade: "2010s" },
  { title: "Let Her Go", artist: "Passenger", decade: "2010s" },
  { title: "Budapest", artist: "George Ezra", decade: "2010s" },
  { title: "Tennessee Whiskey", artist: "Chris Stapleton", decade: "2010s" },
  { title: "Die a Happy Man", artist: "Thomas Rhett", decade: "2010s" },
  { title: "Body Like a Back Road", artist: "Sam Hunt", decade: "2010s" },
  { title: "Cruise", artist: "Florida Georgia Line", decade: "2010s" },
  { title: "The Bones", artist: "Maren Morris", decade: "2010s" },
  { title: "Tear in My Heart", artist: "Twenty One Pilots", decade: "2010s" },
  { title: "Youth", artist: "Troye Sivan", decade: "2010s" },
  { title: "Sunflower", artist: "Post Malone & Swae Lee", decade: "2010s" },
  { title: "Rockstar", artist: "Post Malone ft. 21 Savage", decade: "2010s" },
  { title: "Congratulations", artist: "Post Malone ft. Quavo", decade: "2010s" },
  { title: "Sicko Mode", artist: "Travis Scott", decade: "2010s" },



  { title: "Wildest Dreams", artist: "Taylor Swift", decade: "2010s" },
  { title: "Delicate", artist: "Taylor Swift", decade: "2010s" },
  { title: "Me!", artist: "Taylor Swift ft. Brendon Urie", decade: "2010s" },
  { title: "Landslide (Live)", artist: "Dixie Chicks", decade: "2010s" },
  { title: "Back to December", artist: "Taylor Swift", decade: "2010s" },
  { title: "You Belong with Me", artist: "Taylor Swift", decade: "2010s" },
  { title: "Take Back the Night", artist: "Justin Timberlake", decade: "2010s" },
  { title: "Suit & Tie", artist: "Justin Timberlake ft. Jay-Z", decade: "2010s" },
  { title: "Work B**ch", artist: "Britney Spears", decade: "2010s" },
  { title: "Hold It Against Me", artist: "Britney Spears", decade: "2010s" },
  { title: "Your Love Is My Drug", artist: "Kesha", decade: "2010s" },
  { title: "Die Young", artist: "Kesha", decade: "2010s" },
  { title: "Till the World Ends", artist: "Britney Spears", decade: "2010s" },
  { title: "Starboy", artist: "The Weeknd ft. Daft Punk", decade: "2010s" },
  { title: "The Hills", artist: "The Weeknd", decade: "2010s" },
  { title: "Call Out My Name", artist: "The Weeknd", decade: "2010s" },
  { title: "Young Dumb & Broke", artist: "Khalid", decade: "2010s" },
  { title: "Talk", artist: "Khalid", decade: "2010s" },
  { title: "Better", artist: "Khalid", decade: "2010s" },
  { title: "Ocean Eyes", artist: "Billie Eilish", decade: "2010s" },
  { title: "My Future", artist: "Billie Eilish", decade: "2010s" },
  { title: "Say You Won’t Let Go", artist: "James Arthur", decade: "2010s" },
  { title: "Let Me Love You", artist: "DJ Snake ft. Justin Bieber", decade: "2010s" },
  { title: "2U", artist: "David Guetta ft. Justin Bieber", decade: "2010s" },
  { title: "Titanium", artist: "David Guetta ft. Sia", decade: "2010s" },
  { title: "Chandelier", artist: "Sia", decade: "2010s" },
  { title: "Elastic Heart", artist: "Sia", decade: "2010s" },
  { title: "Cheap Thrills", artist: "Sia ft. Sean Paul", decade: "2010s" },
  { title: "Lush Life", artist: "Zara Larsson", decade: "2010s" },
  { title: "Ain’t My Fault", artist: "Zara Larsson", decade: "2010s" },
  { title: "Symphony", artist: "Clean Bandit ft. Zara Larsson", decade: "2010s" },
  { title: "Wake Me Up", artist: "Avicii", decade: "2010s" },
  { title: "Hey Brother", artist: "Avicii", decade: "2010s" },
  { title: "Without You", artist: "Avicii ft. Sandro Cavazza", decade: "2010s" },
  { title: "Animals", artist: "Martin Garrix", decade: "2010s" },
  { title: "Scared to Be Lonely", artist: "Martin Garrix & Dua Lipa", decade: "2010s" },
  { title: "New Rules", artist: "Dua Lipa", decade: "2010s" },
  { title: "IDGAF", artist: "Dua Lipa", decade: "2010s" },
  { title: "Electricity", artist: "Silk City & Dua Lipa", decade: "2010s" },
  { title: "Him & I", artist: "G-Eazy & Halsey", decade: "2010s" },
  { title: "Bad at Love", artist: "Halsey", decade: "2010s" },
  { title: "Now or Never", artist: "Halsey", decade: "2010s" },
  { title: "Be Alright", artist: "Dean Lewis", decade: "2010s" },
  { title: "7 Years", artist: "Lukas Graham", decade: "2010s" },
  { title: "Mama", artist: "Jonas Blue ft. William Singe", decade: "2010s" },
  { title: "Perfect Strangers", artist: "Jonas Blue ft. JP Cooper", decade: "2010s" },
  { title: "There’s Nothing Holdin’ Me Back", artist: "Shawn Mendes", decade: "2010s" },
  { title: "Treat You Better", artist: "Shawn Mendes", decade: "2010s" },
  { title: "Lost in Japan", artist: "Shawn Mendes", decade: "2010s" },
  




  { title: "Blinding Lights", artist: "The Weeknd", decade: "2020s" },
  { title: "Save Your Tears", artist: "The Weeknd", decade: "2020s" },
  { title: "Levitating", artist: "Dua Lipa", decade: "2020s" },
  { title: "Don't Start Now", artist: "Dua Lipa", decade: "2020s" },
  { title: "As It Was", artist: "Harry Styles", decade: "2020s" },
  { title: "Watermelon Sugar", artist: "Harry Styles", decade: "2020s" },
  { title: "Bad Habits", artist: "Ed Sheeran", decade: "2020s" },
  { title: "Shivers", artist: "Ed Sheeran", decade: "2020s" },
  { title: "Flowers", artist: "Miley Cyrus", decade: "2020s" },
  { title: "Midnight Sky", artist: "Miley Cyrus", decade: "2020s" },
  { title: "Anti-Hero", artist: "Taylor Swift", decade: "2020s" },
  { title: "Lavender Haze", artist: "Taylor Swift", decade: "2020s" },
  { title: "Cardigan", artist: "Taylor Swift", decade: "2020s" },
  { title: "Good 4 U", artist: "Olivia Rodrigo", decade: "2020s" },
  { title: "Drivers License", artist: "Olivia Rodrigo", decade: "2020s" },
  { title: "Vampire", artist: "Olivia Rodrigo", decade: "2020s" },
  { title: "Montero (Call Me By Your Name)", artist: "Lil Nas X", decade: "2020s" },
  { title: "Industry Baby", artist: "Lil Nas X & Jack Harlow", decade: "2020s" },
  { title: "First Class", artist: "Jack Harlow", decade: "2020s" },
  { title: "Circles", artist: "Post Malone", decade: "2020s" },
  { title: "Sunflower", artist: "Post Malone & Swae Lee", decade: "2020s" },
  { title: "Stay", artist: "The Kid LAROI & Justin Bieber", decade: "2020s" },
  { title: "Peaches", artist: "Justin Bieber ft. Daniel Caesar & Giveon", decade: "2020s" },
  { title: "Die For You", artist: "The Weeknd", decade: "2020s" },
  { title: "Heat Waves", artist: "Glass Animals", decade: "2020s" },
  { title: "Super Freaky Girl", artist: "Nicki Minaj", decade: "2020s" },
  { title: "Big Energy", artist: "Latto", decade: "2020s" },
  { title: "Break My Soul", artist: "Beyoncé", decade: "2020s" },
  { title: "Cuff It", artist: "Beyoncé", decade: "2020s" },
  { title: "Kill Bill", artist: "SZA", decade: "2020s" },
  { title: "Snooze", artist: "SZA", decade: "2020s" },
  { title: "Boy’s a Liar Pt. 2", artist: "PinkPantheress & Ice Spice", decade: "2020s" },
  { title: "Barbie World", artist: "Nicki Minaj & Ice Spice", decade: "2020s" },
  { title: "Calm Down", artist: "Rema & Selena Gomez", decade: "2020s" },
  { title: "TQG", artist: "Karol G & Shakira", decade: "2020s" },
  { title: "Bzrp Music Sessions, Vol. 53", artist: "Shakira & Bizarrap", decade: "2020s" },
  { title: "Euphoria", artist: "Jungkook", decade: "2020s" },
  { title: "Seven", artist: "Jungkook ft. Latto", decade: "2020s" },
  { title: "Butter", artist: "BTS", decade: "2020s" },
  { title: "Dynamite", artist: "BTS", decade: "2020s" },
  { title: "Tití Me Preguntó", artist: "Bad Bunny", decade: "2020s" },
  { title: "Me Porto Bonito", artist: "Bad Bunny & Chencho Corleone", decade: "2020s" },
  { title: "Dakiti", artist: "Bad Bunny & Jhay Cortez", decade: "2020s" },
  { title: "I Like You (A Happier Song)", artist: "Post Malone & Doja Cat", decade: "2020s" },
  { title: "Say So", artist: "Doja Cat", decade: "2020s" },
  { title: "Need to Know", artist: "Doja Cat", decade: "2020s" },
  { title: "Paint the Town Red", artist: "Doja Cat", decade: "2020s" },
  { title: "Shirt", artist: "SZA", decade: "2020s" },
  { title: "Unholy", artist: "Sam Smith & Kim Petras", decade: "2020s" },
  { title: "My Universe", artist: "Coldplay & BTS", decade: "2020s" },
  { title: "Golden", artist: "Harry Styles", decade: "2020s" },
  { title: "Late Night Talking", artist: "Harry Styles", decade: "2020s" },
  { title: "Music for a Sushi Restaurant", artist: "Harry Styles", decade: "2020s" },
  { title: "Stupid Love", artist: "Lady Gaga", decade: "2020s" },
  { title: "Rain on Me", artist: "Lady Gaga & Ariana Grande", decade: "2020s" },
  { title: "911", artist: "Lady Gaga", decade: "2020s" },
  { title: "Midnight Rain", artist: "Taylor Swift", decade: "2020s" },
  { title: "Bejeweled", artist: "Taylor Swift", decade: "2020s" },
  { title: "Paris", artist: "Taylor Swift", decade: "2020s" },
  { title: "Boyfriend", artist: "Dove Cameron", decade: "2020s" },
  { title: "abcdefu", artist: "GAYLE", decade: "2020s" },
  { title: "Nonsense", artist: "Sabrina Carpenter", decade: "2020s" },
  { title: "Feather", artist: "Sabrina Carpenter", decade: "2020s" },
  { title: "Lottery", artist: "Latto ft. LU KALA", decade: "2020s" },
  { title: "No Body, No Crime", artist: "Taylor Swift ft. HAIM", decade: "2020s" },
  { title: "Monster", artist: "Shawn Mendes & Justin Bieber", decade: "2020s" },
  { title: "Summer Baby", artist: "Jonas Brothers", decade: "2020s" },
  { title: "What a Man Gotta Do", artist: "Jonas Brothers", decade: "2020s" },
  { title: "Only Wanna Be With You (Pokémon 25 Version)", artist: "Post Malone", decade: "2020s" },
  { title: "Selfish", artist: "Justin Timberlake", decade: "2020s" },
  { title: "Trollz", artist: "6ix9ine & Nicki Minaj", decade: "2020s" },
  { title: "Superhero (Heroes & Villains)", artist: "Metro Boomin, Future & Chris Brown", decade: "2020s" },
  { title: "On BS", artist: "Drake & 21 Savage", decade: "2020s" },
  { title: "Spin Bout U", artist: "Drake & 21 Savage", decade: "2020s" },
  { title: "Broke Boys", artist: "Drake & 21 Savage", decade: "2020s" },
  { title: "Rich Flex", artist: "Drake & 21 Savage", decade: "2020s" },
  { title: "Finesse Out The Gang Way", artist: "Lil Durk ft. Lil Baby", decade: "2020s" },
  { title: "Who Want Smoke?", artist: "Nardo Wick ft. G Herbo, Lil Durk & 21 Savage", decade: "2020s" },
  { title: "Calling My Phone", artist: "Lil Tjay ft. 6LACK", decade: "2020s" },
  { title: "The Color Violet", artist: "Tory Lanez", decade: "2020s" },
  { title: "Water", artist: "Tyla", decade: "2020s" },
  { title: "Escapism", artist: "RAYE ft. 070 Shake", decade: "2020s" },
  { title: "Pain", artist: "PinkPantheress", decade: "2020s" },
  { title: "Obsessed", artist: "Calvin Harris, Shenseea & Charlie Puth", decade: "2020s" },
  { title: "Bebe Dame", artist: "Fuerza Regida & Grupo Frontera", decade: "2020s" },
  { title: "Ella Baila Sola", artist: "Eslabon Armado & Peso Pluma", decade: "2020s" },
  { title: "Padam Padam", artist: "Kylie Minogue", decade: "2020s" },
{ title: "Rush", artist: "Troye Sivan", decade: "2020s" },
{ title: "One of Your Girls", artist: "Troye Sivan", decade: "2020s" },
{ title: "10:35", artist: "Tiësto & Tate McRae", decade: "2020s" },
{ title: "Greedy", artist: "Tate McRae", decade: "2020s" },
{ title: "Cha Cha Cha", artist: "Käärijä", decade: "2020s" },
{ title: "Unstoppable", artist: "Sia", decade: "2020s" },
{ title: "Running Up That Hill (A Deal with God)", artist: "Kate Bush", decade: "2020s" },
{ title: "Ghost", artist: "Justin Bieber", decade: "2020s" },
{ title: "Love Again", artist: "Dua Lipa", decade: "2020s" },
{ title: "Dance The Night", artist: "Dua Lipa", decade: "2020s" },
{ title: "Psycho", artist: "Anne-Marie & Aitch", decade: "2020s" },
{ title: "Eyes Closed", artist: "Ed Sheeran", decade: "2020s" },
{ title: "End of Beginning", artist: "Djo", decade: "2020s" },
{ title: "Texas Hold 'Em", artist: "Beyoncé", decade: "2020s" },
{ title: "My Love Mine All Mine", artist: "Mitski", decade: "2020s" },
{ title: "Angel", artist: "Halle Bailey", decade: "2020s" },
{ title: "Greedy", artist: "Ariana Grande", decade: "2020s" },
{ title: "Yes, And?", artist: "Ariana Grande", decade: "2020s" },
{ title: "Rockstar", artist: "DaBaby ft. Roddy Ricch", decade: "2020s" },
{ title: "For The Night", artist: "Pop Smoke ft. Lil Baby & DaBaby", decade: "2020s" },
{ title: "Calling", artist: "Metro Boomin, The Weeknd & 21 Savage", decade: "2020s" },
{ title: "Popular", artist: "The Weeknd, Madonna & Playboi Carti", decade: "2020s" },
{ title: "Chemical", artist: "Post Malone", decade: "2020s" },
{ title: "Mourning", artist: "Post Malone", decade: "2020s" },
{ title: "Baddadan", artist: "Chase & Status & Bou ft. Flowdan, Trigga, Irah & Takura", decade: "2020s" },
{ title: "Turn The Lights Back On", artist: "Billy Joel", decade: "2020s" },
{ title: "Espresso", artist: "Sabrina Carpenter", decade: "2020s" },
{ title: "What Was I Made For?", artist: "Billie Eilish", decade: "2020s" },
{ title: "Work Song", artist: "Hozier", decade: "2010s" },
{ title: "Jolene", artist: "Beyoncé", decade: "2020s" },
{ title: "Picture", artist: "Kid Rock featuring Sheryl Crow", decade: "2000s" },
{ title: "In the End", artist: "Linkin Park", decade: "2000s" },
{ title: "Too Sweet", artist: "Hozier", decade: "2020s" },
{ title: "What You Won’t Do for Love", artist: "Bobby Caldwell", decade: "1970s" },
{ title: "Beautiful Things", artist: "Benson Boone", decade: "2020s" },
{ title: "Lose Control", artist: "Teddy Swims", decade: "2020s" },
{ title: "Accidentally in Love", artist: "Counting Crows", decade: "2000s" },
{ title: "Out Tonight", artist: "Rent (Movie Version)", decade: "2000s" },
{ title: "Death of a Bachelor", artist: "Panic! At The Disco", decade: "2010s" },
{ title: "Love Song", artist: "Sara Bareilles", decade: "2000s" },
{ title: "Perfect", artist: "Ed Sheeran", decade: "2010s" },
{ title: "She Will Be Loved", artist: "Maroon 5", decade: "2000s" },
{ title: "Chop Suey", artist: "System of a Down", decade: "2000s" },
{ title: "Someone Like You", artist: "Adele", decade: "2010s" },
{ title: "Face Down", artist: "The Red Jumpsuit Apparatus", decade: "2000s" },
{ title: "Beyond the Sea", artist: "Bobby Darin", decade: "1950s" },
{ title: "Everybody Talks", artist: "Neon Trees", decade: "2010s" },
{ title: "Under the Bridge", artist: "Red Hot Chili Peppers", decade: "1990s" },
{ title: "My Way", artist: "Frank Sinatra", decade: "1960s" },
{ title: "Black", artist: "Pearl Jam", decade: "1990s" },
{ title: "Killing Me Softly", artist: "Lauryn Hill", decade: "1990s" },
{ title: "When You Got a Good Friend", artist: "Eric Clapton", decade: "2000s" },
{ title: "No One", artist: "Alicia Keys", decade: "2000s" },
{ title: "Northern Downpour", artist: "Panic! At The Disco", decade: "2000s" },
{ title: "Lithium", artist: "Evanescence", decade: "2000s" },
{ title: "Somebody to Shove", artist: "Soul Asylum", decade: "1990s" },
{ title: "Do I Wanna Know?", artist: "Arctic Monkeys", decade: "2010s" },
{ title: "B.Y.O.B.", artist: "System of a Down", decade: "2000s" },
{ title: "So What", artist: "P!nk", decade: "2000s" },
{ title: "Titanium", artist: "Sia", decade: "2010s" },
{ title: "One Man Band", artist: "Old Dominion", decade: "2010s" },
{ title: "Got Me Wrong", artist: "Alice in Chains", decade: "1990s" },
{ title: "2AM (Breathe)", artist: "Anna Nalick", decade: "2000s" },
{ title: "Before He Cheats", artist: "Carrie Underwood", decade: "2000s" },
{ title: "Country Roads", artist: "John Denver", decade: "1970s" },
{ title: "Ordinary People", artist: "John Legend", decade: "2000s" },
{ title: "Blinded by the Light", artist: "Manfred Mann's Earth Band", decade: "1970s" },
{ title: "Livin' Thing", artist: "Electric Light Orchestra (ELO)", decade: "1970s" },
{ title: "One Last Breath", artist: "Creed", decade: "2000s" },
{ title: "My Own Worst Enemy", artist: "Lit", decade: "1990s" },
{ title: "July", artist: "Noah Cyrus", decade: "2020s" },
{ title: "Man! I Feel Like a Woman!", artist: "Shania Twain", decade: "1990s" },
{ title: "Travelin' Soldier", artist: "The Chicks", decade: "2000s" },
{ title: "You and I", artist: "Lady Gaga", decade: "2010s" },
{ title: "Don't Take the Girl", artist: "Tim McGraw", decade: "1990s" },
{ title: "All of Me", artist: "John Legend", decade: "2010s" },
{ title: "Me & U", artist: "Cassie", decade: "2000s" }


];

const shuffleArray = (array) => [...array].sort(() => Math.random() - 0.5);

// ✅ Moved inside the component
const [randomSelection, setRandomSelection] = useState(null);
const [isDropdownOpen, setIsDropdownOpen] = useState(false);
const [selectedDecade, setSelectedDecade] = useState("ALL");

// Get unique decades for dropdown
const decades = ["ALL", ...new Set(songs.map(song => song.decade))];

// Filtered song list based on selected decade
const filteredSongs = selectedDecade === "ALL" ? songs : songs.filter(song => song.decade === selectedDecade);

// ✅ Ensure the songQueue is updated when the decade changes
const [songQueue, setSongQueue] = useState(shuffleArray([...filteredSongs]));
const [artistQueue, setArtistQueue] = useState(shuffleArray([...new Set(songs.map(song => song.artist))]));

// ✅ Update songQueue whenever selectedDecade changes
useEffect(() => {
    setSongQueue(shuffleArray([...filteredSongs]));
    setArtistQueue(shuffleArray([...new Set(filteredSongs.map(song => song.artist))]));
}, [selectedDecade]);


// Function to pick a random song
const pickRandomSong = () => {
    if (songQueue.length === 0) {
        setSongQueue(shuffleArray([...filteredSongs]));
    }
    const nextSong = songQueue.pop();
    setSongQueue([...songQueue]); 
    setRandomSelection(nextSong || null);
};

// Function to pick a random artist
const pickRandomArtist = () => {
    if (artistQueue.length === 0) {
        setArtistQueue(shuffleArray([...new Set(filteredSongs.map(song => song.artist))]));
    }
    const nextArtist = artistQueue.pop();
    setArtistQueue([...artistQueue]); // Update queue state
    setRandomSelection(nextArtist ? { artist: nextArtist } : null);
};



return (
    <>
        {/* Dropdown Button */}
        <button 
            type="button"
            className="w-full bg-gradient-to-r from-purple-500 to-indigo-500 text-white font-semibold py-3 px-6 rounded-xl shadow-lg hover:shadow-xl transition-all duration-300 transform hover:scale-105"
            onClick={(event) => {
                event.preventDefault(); // Prevent form submission
                setIsDropdownOpen(!isDropdownOpen);
            }}
        >
            Random Song Generator ⬇️
        </button>

        {isDropdownOpen && (
            <>
                {/* Decade Dropdown */}
                <div className="relative mt-4 w-full">
  <select
    className="w-full px-4 py-3 bg-white text-gray-800 rounded-xl border border-gray-300 shadow-md focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 transition-all duration-300 cursor-pointer hover:bg-gray-100"
    value={selectedDecade}
    onChange={(e) => setSelectedDecade(e.target.value)}
  >
    {[...decades].sort((a, b) => b.localeCompare(a)).map(decade => (
      <option key={decade} value={decade} className="text-gray-900">
        {decade}
      </option>
    ))}
  </select>
  <div className="absolute top-1/2 right-4 transform -translate-y-1/2 pointer-events-none">
    ⏳ {/* Replace with an actual dropdown icon if needed */}
  </div>
</div>


                {/* Buttons for Random Song & Artist */}
                <div className="flex w-full flex-col items-center space-y-4 mt-4">
                    <button 
                        type="button" 
                        onClick={(event) => {
                            event.preventDefault(); // Prevent form submission
                            pickRandomSong();
                        }} 
                        className="px-6 py-3 bg-blue-600 text-white font-medium rounded-3xl w-full shadow-md shadow-pink-400 hover:bg-blue-700 transition-all duration-300 transform hover:scale-105"
                    >
                        Random Song 🎶
                    </button>

                    <button 
                        type="button" 
                        onClick={(event) => {
                            event.preventDefault(); // Prevent form submission
                            pickRandomArtist();
                        }} 
                        className="w-full py-3 bg-green-600 text-white font-medium rounded-3xl shadow-md shadow-yellow-300 hover:bg-green-700 transition-all duration-300 transform hover:scale-105"
                    >
                        Random Artist 🎤
                    </button>
                </div>

                {/* Display Selected Song or Artist */}
                <div className="w-full mt-6">
    {randomSelection && (
        <div
            className="cursor-pointer  p-10 pb-2 pt-2 text-center bg-gradient-to-b from-blue-400 via-blue-600 to-blue-800 text-white rounded-2xl shadow-lg hover:scale-105 hover:shadow-2xl transition-transform duration-300 ease-in-out"
            onClick={() => onSelect && onSelect(randomSelection)}
        >
            {randomSelection.title ? (
                <div className="max-h-20 w-full overflow-auto scrollbar-thin scrollbar-thumb-pink-500 scrollbar-track-gray-300">
                    <p className="text-xl  font-bold  tracking-wide">{randomSelection.title}</p>
                    <p className="text-lg text-gray-200 font-bold italic mt-1">{randomSelection.artist}</p>
                    <p className="text-sm text-gray-300 italic mt-1">({randomSelection.decade})</p>
                </div>
            ) : (
                <p className="text-xl font-semibold">
                    🎤 <span className="block text-2xl font-bold mt-2">{randomSelection.artist}</span>
                </p>
            )}
            <p className="text-sm text-gray-200 italic mt-4 animate-pulse">(Click to autofill)</p>
        </div>
    )}
</div>

            </>
        )}
    </>
);
};

export default RandomSongGenerator;